version: '3'

services:
  erlang:
    container_name: erlang
    image: emqx/build-env:erl23.2.2-ubuntu20.04
    volumes:
      - ../../:/emqx
    working_dir: /emqx
    networks:
      - emqx_bridge
    depends_on:
      - mongo_server
    tty: true

  mongo_server:
    container_name: mongo
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mqtt
    volumes:
        - ../../apps/emqx_auth_mongo/test/emqx_auth_mongo_SUITE_data/mongodb.pem/:/etc/certs/mongodb.pem
    networks:
      - emqx_bridge
    command:
      --ipv6
      --bind_ip_all
      --sslMode requireSSL
      --sslPEMKeyFile /etc/certs/mongodb.pem

networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.100.0/24
          gateway: 172.100.100.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
