version: '3'

services:
  erlang:
    container_name: erlang
    image: emqx/build-env:erl23.2.2-ubuntu20.04
    volumes:
      - ../../:/emqx
    working_dir: /emqx
    networks:
      - emqx_bridge
    depends_on:
      - pgsql_server
    tty: true

  pgsql_server:
    container_name: pgsql
    image: postgres:${PGSQL_TAG}
    restart: always
    environment:
      POSTGRES_PASSWORD: public
      POSTGRES_USER: root
      POSTGRES_DB: mqtt
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.100.0/24
          gateway: 172.100.100.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
