version: '3'

services:
  erlang:
    container_name: erlang
    image: emqx/build-env:erl23.2.2-ubuntu20.04
    volumes:
      - ../../:/emqx
    working_dir: /emqx
    networks:
      - emqx_bridge
    depends_on:
      - mysql_server
    tty: true

  mysql_server:
    container_name: mysql
    image: mysql:${MYSQL_TAG}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
    networks:
      - emqx_bridge
    command:
      --bind-address "::"
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --skip-symbolic-links

networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.100.0/24
          gateway: 172.100.100.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
