name: Run gitlint

on: [pull_request]

jobs:
  run_gitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Code dialyzer
        run: |
          sudo apt-get update
          sudo apt install gitlint
      - name: Run tests
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          messages=$(curl "https://api.github.com/repos/emqx/emqx/pulls/${pull_number}/commits")
          len=$(echo $messages | jq length)
          result=true
          for i in $( seq 0 $(($len - 1)) ); do
            message=$(echo $messages | jq -r .[$i].commit.message)
            echo commit message: $message
            status=0
            echo $message | gitlint -C ./.github/workflows/.gitlint || status=$?
            if [ $status -ne 0 ]; then
              result=false
            fi
          done
          if ! ${result} ; then
            echo "Some of the commit messages are not structured as The Conventional Commits specification. Please check CONTRIBUTING.md for our process on contribution."
            exit 1
          fi
